//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KinoCentar.WinUI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KinoCentar.WinUI.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali podatke o žanru..
        /// </summary>
        internal static string add_genre_succ {
            get {
                return ResourceManager.GetString("add_genre_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali podatke o jednici mjere..
        /// </summary>
        internal static string add_jedMjere_succ {
            get {
                return ResourceManager.GetString("add_jedMjere_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste dodali salu..
        /// </summary>
        internal static string add_sale_succ {
            get {
                return ResourceManager.GetString("add_sale_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li želite izbrisati žanr?.
        /// </summary>
        internal static string del_genre_prompt {
            get {
                return ResourceManager.GetString("del_genre_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste obrisali podatke o žarnu..
        /// </summary>
        internal static string del_genre_succ {
            get {
                return ResourceManager.GetString("del_genre_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li želite izbrisati jedinicu mjere?.
        /// </summary>
        internal static string del_jedMjere_prompt {
            get {
                return ResourceManager.GetString("del_jedMjere_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste obrisali podatke o jedinici mejre..
        /// </summary>
        internal static string del_jedMjere_succ {
            get {
                return ResourceManager.GetString("del_jedMjere_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li želite izbrisati salu?.
        /// </summary>
        internal static string del_sale_prompt {
            get {
                return ResourceManager.GetString("del_sale_prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste obrisali salu..
        /// </summary>
        internal static string del_sale_succ {
            get {
                return ResourceManager.GetString("del_sale_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmijenili podatke o žanru..
        /// </summary>
        internal static string edit_genre_succ {
            get {
                return ResourceManager.GetString("edit_genre_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmjenili podatke o jednici mjere..
        /// </summary>
        internal static string edit_jedMjere_succ {
            get {
                return ResourceManager.GetString("edit_jedMjere_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uspješno ste izmjenili podatke o sali..
        /// </summary>
        internal static string edit_sale_succ {
            get {
                return ResourceManager.GetString("edit_sale_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv žanra treba da sadrži najmanje 3 karaktera..
        /// </summary>
        internal static string genre_name_err {
            get {
                return ResourceManager.GetString("genre_name_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv žanra je obavezan..
        /// </summary>
        internal static string genre_name_req {
            get {
                return ResourceManager.GetString("genre_name_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv žanra treba da sadrži najmanje 3 karaktera..
        /// </summary>
        internal static string jedMjere_name_err {
            get {
                return ResourceManager.GetString("jedMjere_name_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv žanra je obavezan..
        /// </summary>
        internal static string jedMjere_name_req {
            get {
                return ResourceManager.GetString("jedMjere_name_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kratki naziv žanra treba da sadrži najmanje 3 karaktera..
        /// </summary>
        internal static string jedMjere_shortName_err {
            get {
                return ResourceManager.GetString("jedMjere_shortName_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Da li ste sigurni da želite odustati.
        /// </summary>
        internal static string msg_cancel_que {
            get {
                return ResourceManager.GetString("msg_cancel_que", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Potvrda.
        /// </summary>
        internal static string msg_conf {
            get {
                return ResourceManager.GetString("msg_conf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poruka o uspjehu.
        /// </summary>
        internal static string msg_succ {
            get {
                return ResourceManager.GetString("msg_succ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upozorenje.
        /// </summary>
        internal static string msg_war {
            get {
                return ResourceManager.GetString("msg_war", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj sjedišta sale je obavezan..
        /// </summary>
        internal static string sale_brojSjedista_req {
            get {
                return ResourceManager.GetString("sale_brojSjedista_req", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv sale treba da sadrži najmanje 3 karaktera..
        /// </summary>
        internal static string sale_name_err {
            get {
                return ResourceManager.GetString("sale_name_err", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naziv sale je obavezan..
        /// </summary>
        internal static string sale_name_req {
            get {
                return ResourceManager.GetString("sale_name_req", resourceCulture);
            }
        }
    }
}
